name: bbm_backend_dev
description: "BBM Backend Service"
version: 1.0.0+1
environment:
  sdk: ^3.6.2
dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  http_parser: ^4.0.2
  firebase_admin: ^0.3.0+1
  asn1lib: 1.5.8
  http: ^1.3.0
  firebase_core: 3.12.1
dev_dependencies:
  lints: ^4.0.0