services:
  - type: web
    name: bbm-backend-dev
    env: docker
    region: oregon
    plan: free
    rootDir: lib  # Point to the lib directory where your code is
    healthCheckPath: /test
    envVars:
      - key: PORT
        value: 8080
      - key: FIREBASE_PROJECT_ID
        value: bbm-db-dev  # Your Firebase project ID
      - key: FIREBASE_PRIVATE_KEY
        sync: false  # Will be set manually in dashboard
      - key: FIREBASE_CLIENT_EMAIL
        sync: false  # Will be set manually in dashboard