services:
  - type: web
    name: bbm-backend-dev
    env: docker
    region: oregon
    plan: free
    rootDir: bbm-backend-dev  # This matches your folder structure
    healthCheckPath: /test
    envVars:
      - key: PORT
        value: 8080
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false