name: Deploy Dart Server to Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Enable manual triggering

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Setup Dart SDK
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.6.2'
      
      # Install dependencies
      - name: Install dependencies
        run: dart pub get
      
      # Run tests
      - name: Run tests
        run: dart test
      
      # Build Docker image
      - name: Build and push Docker image
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: bbm-db-dev
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      
      - name: Build Docker image
        run: |
          gcloud builds submit --tag gcr.io/bbm-db-dev/bbm-backend-api
      
      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy bbm-backend-api \
            --image gcr.io/bbm-db-dev/bbm-backend-api \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated
